// <auto-generated />
using System;
using APIColegio.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace APIColegio.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("APIColegio.Models.Alumno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaIngreso")
                        .HasColumnType("date")
                        .HasColumnName("fecha_ingreso");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("date")
                        .HasColumnName("fecha_nacimiento");

                    b.Property<string>("Grado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("grado");

                    b.Property<string>("NombreAlumno")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre_alumno");

                    b.Property<string>("NombreMadre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre_madre");

                    b.Property<string>("NombrePadre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre_padre");

                    b.Property<string>("Seccion")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("seccion");

                    b.HasKey("Id");

                    b.HasIndex("Grado")
                        .HasDatabaseName("idx_alumnos_grado");

                    b.HasIndex("Seccion")
                        .HasDatabaseName("idx_alumnos_seccion");

                    b.ToTable("alumnos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FechaIngreso = new DateTime(2021, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaNacimiento = new DateTime(2010, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Grado = "5to",
                            NombreAlumno = "Juan Pérez García",
                            NombreMadre = "María García Hernández",
                            NombrePadre = "Carlos Pérez López",
                            Seccion = "A"
                        },
                        new
                        {
                            Id = 2,
                            FechaIngreso = new DateTime(2020, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaNacimiento = new DateTime(2009, 8, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Grado = "6to",
                            NombreAlumno = "Ana López Martínez",
                            NombreMadre = "Carmen Martínez Rodríguez",
                            NombrePadre = "Roberto López Silva",
                            Seccion = "B"
                        },
                        new
                        {
                            Id = 3,
                            FechaIngreso = new DateTime(2022, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaNacimiento = new DateTime(2011, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Grado = "4to",
                            NombreAlumno = "Luis Fernández Ruiz",
                            NombreMadre = "Laura Ruiz Morales",
                            NombrePadre = "José Fernández Castro",
                            Seccion = "A"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
